library(shiny)
library(dplyr)
library(shinyWidgets)
library(tidycovid19)
library(rclipboard)
library(lubridate)

load("shiny_data.Rda")

if(difftime(now(tzone = "Europe/Berlin"), shiny_data$timestamp[1]) > 24)
  shiny_df <- download_merged_data(cached = TRUE, silent = TRUE)

ui <- fluidPage(
  rclipboardSetup(),
  titlePanel("Explore the Spread of Covid-19"),
  tags$p(
    "This display is based on data",
    tags$ul(
      tags$li("from the",
              tags$a(href = "https://github.com/CSSEGISandData/COVID-19",
                     "Johns Hopkins University CSSE team"),
              "on the spread of the SARS-CoV-2 virus"),
      tags$li("from the",
              tags$a(href = "https://www.acaps.org/covid19-government-measures-dataset",
                     "ACAPS governmental measures database"),
              "and"),
      tags$li(HTML(paste0("from the ",
              tags$a(href = "https://data.worldbank.org", "World Bank"), ".")))
    ),
    "It has been inpired by the displays created by John Burn-Murdoch",
    "for the Financial Times."
  ),
  hr(),

  sidebarLayout(
    sidebarPanel(
      radioButtons(
        "type", "Which statistics do you want to display?",
        c("Confirmed Cases" = "confirmed", "Reported deaths" = "deaths",
          "Recovered Cases" = "recovered"),
        "deaths"
      ),
      sliderInput(
        "min_cases",
        "Number of cases to mark day zero on X-axis",
        min = 1, max = 1000, value = 100
      ),
      sliderInput(
        "min_by_ctry_obs",
        "Required number of days to include country",
        min = 1, max = 30, value = 7
      ),
      sliderInput(
        "edate_cutoff",
        "How many days do you want to display?",
        min = 10, max = 90, value = 30
      ),
      checkboxInput(
        "per_capita",
        "Display relative to population (per capita)",
        FALSE
      ),
      checkboxInput(
        "log_scale",
        "Use logarithmic scaling for Y-axis",
        TRUE
      ),
      selectInput(
        "intervention",
        "Select intervention type to highlight by points",
        c("None" = "none", "General lockdowns" = "lockdown",
          "Social distancing"= 'soc_dist', "Movement restrictions" = 'mov_rest',
          "Public health measures" = 'pub_health',
          "Social and economic measures" = 'soc_econ'),
        "none"
      ),
      uiOutput("SelectCountriesHL"),
      uiOutput("SendCodeToClipboard")
    ),
    mainPanel(div(
      style = "position:relative",
      plotOutput(
        "Covid19Plot", width = "100%", height = "600px",
        hover = hoverOpts("plot_hover", delay = 100, delayType = "debounce"))
    ),
    uiOutput("Covid19PlotHover"),
    hr(),
    HTML("<p><center>Based on the <a href=https://joachim-gassen.github.io/tidycovid19>",
         "{tidycovid19} R Package</a>, <a href=https://twitter.com/JoachimGassen>",
         "Joachim Gassen</a>,<br>",
         "<a href=https://www.wiwi.hu-berlin.de/rewe>",
         "Humboldt-Universität zu Berlin</a> and",
         "<a href=https://www.accounting-for-transparency.de>",
         "TRR 266 Accounting for Transparency</a>, 2020</center></p>")

    )),
)

server <- function(input, output) {
  df <- shiny_data

  dyn_data <- reactive({
    df %>%
      group_by(iso3c) %>%
      filter(!! sym(input$type) >= input$min_cases) %>%
      mutate(edate = as.numeric(date - min(date))) %>%
      filter(!is.na(edate)) %>%
      group_by(iso3c) %>%
      filter(n() >= input$min_by_ctry_obs) %>%
      ungroup() %>%
      filter(edate <= input$edate_cutoff) -> df_temp

    if (input$per_capita) df_temp <- df_temp %>%
        mutate(!! input$type := 1e5*(!! sym(input$type))/population) %>%
        filter(!is.na(!! sym(input$type)))

    return(df_temp)
  })

  ctry_selected <- reactiveVal("all")

  ctry_list <- reactive({
    dyn_data() %>%
      select(iso3c, country) %>%
      unique() -> ctries_temp
    ctries <- ctries_temp$iso3c
    names(ctries) <- ctries_temp$country
    ctries <- ctries[order(ctries_temp$country)]
    if (isolate(ctry_selected()[1]) == "all") ctry_selected(ctries)
    else ctry_selected(isolate(ctry_selected()[ctry_selected() %in% ctries]))
    return(ctries)
  })

  plot_code <- reactive({
     paste(
      sep = "\n",
      '# Code generated by shiny_covid19_spread() of the {tidycovid19} package',
      '# See: https://github.com/joachim-gassen/tidycovid19',
      '# Run in R/Rstudio. See https://www.r-project.org and https://www.rstudio.com',
      '# Uncomment the following to install the {tidycovid19} package',
      '',
      '# remotes::install_github("joachim-gassen/tidycovid19)',
      '',
      'library(tidycovid19)',
      '',
      'plot_covid19_spread(',
      sprintf('  type = "%s", min_cases = %d, min_by_ctry_obs = %d,',
              input$type, input$min_cases, input$min_by_ctry_obs),
      sprintf('  edate_cutoff = %d, per_capita = %s, log_scale = %s,',
              input$edate_cutoff, as.character(input$per_capita),
              as.character(input$log_scale)),
      paste0(strwrap(sprintf('  highlight = %s,',
              paste0(capture.output(dput(unname(input$highlight))), collapse = "")), 66),
              collapse = "\n  "),
      sprintf('  intervention = %s',
              ifelse(input$intervention == "none", "NULL",
                     paste0('"', input$intervention, '"'))),
      ')'
    )
  })

  observeEvent(input$highlight, {
    ctry_sel <- isolate(ctry_selected())
    if (length(input$highlight) != length(ctry_sel) ||
        !all(input$highlight %in% ctry_sel))
      ctry_selected(input$highlight)
  })

  output$SelectCountriesHL <- renderUI(
    pickerInput(
      inputId = "highlight",
      label = "Which countries do you want to highlight?",
      choices = ctry_list(),
      selected = isolate(ctry_selected()),
      options = list(
        `actions-box` = TRUE,
        size = 10,
        `selected-text-format` = "count > 3"
      ),
      multiple = TRUE
    )
  )

  output$SendCodeToClipboard <- renderUI({
    rclipButton("clipbtn", "Send Code for Plot to Clipboard",
                plot_code(), icon("clipboard"))
  })

  output$Covid19Plot <- renderPlot({
    req(input$highlight)
    plot_covid19_spread(
      data = df,
      type = input$type,
      min_cases = input$min_cases,
      min_by_ctry_obs = input$min_by_ctry_obs,
      per_capita = input$per_capita,
      log_scale = input$log_scale,
      edate_cutoff = input$edate_cutoff,
      intervention = if(input$intervention != "none") input$intervention else NULL,
      highlight = input$highlight
    )
  })

  output$Covid19PlotHover <- renderUI({
    req(input$plot_hover)
    hover <- input$plot_hover
    df <- dyn_data()
    if (!is.null(hover)) {
      hover$mapping$x <- "edate"
      hover$mapping$y <- input$type
    }
    point <- nearPoints(df, hover, threshold = 25, maxpoints = 1, addDist = TRUE)
    if (nrow(point) == 0) return(NULL)

    # create style property for tooltip
    # background color is set so tooltip is a bit transparent
    # z-index is set so we are sure are tooltip will be on top
    style <- paste0("position:absolute; background-color: rgba(245, 245, 245, 0.85); ",
                    "left:", hover$coords_img$x + 2, "px; top:", hover$coords_img$y + 2, "px;")
    # actual tooltip created as wellPanel
    panel_text <- sprintf(
      "%s, %s:<br>%s %s", point$country, as.character(point$date),
      format(point[, input$type] %>% pull(), digits = 3, big.mark = ","),
      case_when(
        input$type == "confirmed" ~ "confirmed cases",
        input$type == "deaths" ~ "reported deaths",
        input$type == "recovered" ~ "recoveries"
      )
    )
    if (input$per_capita)
      panel_text <- paste(panel_text, "<br>per 100,000 inhabitants")
    wellPanel(style = style, class = "well-sm", HTML(panel_text))
  })
}

shinyApp(ui = ui, server = server)
