# Generated by use_this::use_pipe()

#' Pipe operator
#'
#' See \code{magrittr::\link[magrittr]{\%>\%}} for details.
#'
#' @name %>%
#' @rdname pipe
#' @keywords internal
#' @export
#' @importFrom magrittr %>%

# Some additional imports (not pipe-related) that do not get exported
# can go here

#' @importFrom rlang ":=" .data
#' @usage lhs \%>\% rhs
NULL
