# Generated by use_this::use_pipe()

#' Pipe operator
#'
#' See \code{magrittr::\link[magrittr:pipe]{\%>\%}} for details.
#'
#' @name %>%
#' @rdname pipe
#' @keywords internal
#' @export
#' @importFrom magrittr %>%

# Some additional imports (not pipe-related) that do not get exported
# can go here

#' @importFrom rlang ":=" .data

# Add some imports to packages used in the shiny app code so
# that R CMD check is happy.

#' @importFrom rclipboard rclipboardSetup
#' @importFrom shinyjs useShinyjs
#' @importFrom shinyWidgets addSpinner
#' @importFrom ggrepel geom_text_repel

#' @usage lhs \%>\% rhs
NULL
